linters:
  enable-all: true
  disable:
    - lll
    - interfacer
    - gomnd
    - godox
    - dogsled
    - funlen
    - wsl
    - exhaustivestruct
    - exhaustive
    - testpackage
    - paralleltest
  fast: false
