---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-uploader
subjects:
  - kind: ServiceAccount
    name: cert-uploader
roleRef:
  kind: ClusterRole
  name: cert-uploader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-uploader
subjects:
  - kind: ServiceAccount
    name: cert-uploader
roleRef:
  kind: Role
  name: cert-uploader
  apiGroup: rbac.authorization.k8s.io
